<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">


<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    
    <title>5. Built-in Exceptions &mdash; Python 3.4.3 documentation</title>
    
    <link rel="stylesheet" href="../_static/pydoctheme.css" type="text/css" />
    <link rel="stylesheet" href="../_static/pygments.css" type="text/css" />
    
    <script type="text/javascript">
      var DOCUMENTATION_OPTIONS = {
        URL_ROOT:    '../',
        VERSION:     '3.4.3',
        COLLAPSE_INDEX: false,
        FILE_SUFFIX: '.html',
        HAS_SOURCE:  true
      };
    </script>
    <script type="text/javascript" src="../_static/jquery.js"></script>
    <script type="text/javascript" src="../_static/underscore.js"></script>
    <script type="text/javascript" src="../_static/doctools.js"></script>
    <script type="text/javascript" src="../_static/sidebar.js"></script>
    <link rel="search" type="application/opensearchdescription+xml"
          title="Search within Python 3.4.3 documentation"
          href="../_static/opensearch.xml"/>
    <link rel="author" title="About these documents" href="../about.html" />
    <link rel="copyright" title="Copyright" href="../copyright.html" />
    <link rel="top" title="Python 3.4.3 documentation" href="../index.html" />
    <link rel="up" title="The Python Standard Library" href="index.html" />
    <link rel="next" title="6. Text Processing Services" href="text.html" />
    <link rel="prev" title="4. Built-in Types" href="stdtypes.html" />
    <link rel="shortcut icon" type="image/png" href="../_static/py.png" />
    <script type="text/javascript" src="../_static/copybutton.js"></script>
    <script type="text/javascript" src="../_static/version_switch.js"></script>
    
 

  </head>
  <body>  
    <div class="related">
      <h3>Navigation</h3>
      <ul>
        <li class="right" style="margin-right: 10px">
          <a href="../genindex.html" title="General Index"
             accesskey="I">index</a></li>
        <li class="right" >
          <a href="../py-modindex.html" title="Python Module Index"
             >modules</a> |</li>
        <li class="right" >
          <a href="text.html" title="6. Text Processing Services"
             accesskey="N">next</a> |</li>
        <li class="right" >
          <a href="stdtypes.html" title="4. Built-in Types"
             accesskey="P">previous</a> |</li>
        <li><img src="../_static/py.png" alt=""
                 style="vertical-align: middle; margin-top: -1px"/></li>
        <li><a href="https://www.python.org/">Python</a> &raquo;</li>
        <li>
          <span class="version_switcher_placeholder">3.4.3</span>
          <a href="../index.html">Documentation</a> &raquo;
        </li>

          <li><a href="index.html" accesskey="U">The Python Standard Library</a> &raquo;</li> 
      </ul>
    </div>    

    <div class="document">
      <div class="documentwrapper">
        <div class="bodywrapper">
          <div class="body">
            
  <div class="section" id="built-in-exceptions">
<span id="bltin-exceptions"></span><h1>5. Built-in Exceptions<a class="headerlink" href="#built-in-exceptions" title="Permalink to this headline">¶</a></h1>
<p id="index-0">In Python, all exceptions must be instances of a class that derives from
<a class="reference internal" href="#BaseException" title="BaseException"><tt class="xref py py-class docutils literal"><span class="pre">BaseException</span></tt></a>.  In a <a class="reference internal" href="../reference/compound_stmts.html#try"><tt class="xref std std-keyword docutils literal"><span class="pre">try</span></tt></a> statement with an <a class="reference internal" href="../reference/compound_stmts.html#except"><tt class="xref std std-keyword docutils literal"><span class="pre">except</span></tt></a>
clause that mentions a particular class, that clause also handles any exception
classes derived from that class (but not exception classes from which <em>it</em> is
derived).  Two exception classes that are not related via subclassing are never
equivalent, even if they have the same name.</p>
<p id="index-1">The built-in exceptions listed below can be generated by the interpreter or
built-in functions.  Except where mentioned, they have an &#8220;associated value&#8221;
indicating the detailed cause of the error.  This may be a string or a tuple of
several items of information (e.g., an error code and a string explaining the
code).  The associated value is usually passed as arguments to the exception
class&#8217;s constructor.</p>
<p>User code can raise built-in exceptions.  This can be used to test an exception
handler or to report an error condition &#8220;just like&#8221; the situation in which the
interpreter raises the same exception; but beware that there is nothing to
prevent user code from raising an inappropriate error.</p>
<p>The built-in exception classes can be subclassed to define new exceptions;
programmers are encouraged to derive new exceptions from the <a class="reference internal" href="#Exception" title="Exception"><tt class="xref py py-exc docutils literal"><span class="pre">Exception</span></tt></a>
class or one of its subclasses, and not from <a class="reference internal" href="#BaseException" title="BaseException"><tt class="xref py py-exc docutils literal"><span class="pre">BaseException</span></tt></a>.  More
information on defining exceptions is available in the Python Tutorial under
<a class="reference internal" href="../tutorial/errors.html#tut-userexceptions"><em>User-defined Exceptions</em></a>.</p>
<p>When raising (or re-raising) an exception in an <a class="reference internal" href="../reference/compound_stmts.html#except"><tt class="xref std std-keyword docutils literal"><span class="pre">except</span></tt></a> or
<a class="reference internal" href="../reference/compound_stmts.html#finally"><tt class="xref std std-keyword docutils literal"><span class="pre">finally</span></tt></a> clause
<tt class="xref py py-attr docutils literal"><span class="pre">__context__</span></tt> is automatically set to the last exception caught; if the
new exception is not handled the traceback that is eventually displayed will
include the originating exception(s) and the final exception.</p>
<p>When raising a new exception (rather than using a bare <tt class="docutils literal"><span class="pre">raise</span></tt> to re-raise
the exception currently being handled), the implicit exception context can be
supplemented with an explicit cause by using <a class="reference internal" href="../reference/simple_stmts.html#from"><tt class="xref std std-keyword docutils literal"><span class="pre">from</span></tt></a> with
<a class="reference internal" href="../reference/simple_stmts.html#raise"><tt class="xref std std-keyword docutils literal"><span class="pre">raise</span></tt></a>:</p>
<div class="highlight-python3"><div class="highlight"><pre><span class="k">raise</span> <span class="n">new_exc</span> <span class="kn">from</span> <span class="nn">original_exc</span>
</pre></div>
</div>
<p>The expression following <a class="reference internal" href="../reference/simple_stmts.html#from"><tt class="xref std std-keyword docutils literal"><span class="pre">from</span></tt></a> must be an exception or <tt class="docutils literal"><span class="pre">None</span></tt>. It
will be set as <tt class="xref py py-attr docutils literal"><span class="pre">__cause__</span></tt> on the raised exception. Setting
<tt class="xref py py-attr docutils literal"><span class="pre">__cause__</span></tt> also implicitly sets the <tt class="xref py py-attr docutils literal"><span class="pre">__suppress_context__</span></tt>
attribute to <tt class="docutils literal"><span class="pre">True</span></tt>, so that using <tt class="docutils literal"><span class="pre">raise</span> <span class="pre">new_exc</span> <span class="pre">from</span> <span class="pre">None</span></tt>
effectively replaces the old exception with the new one for display
purposes (e.g. converting <a class="reference internal" href="#KeyError" title="KeyError"><tt class="xref py py-exc docutils literal"><span class="pre">KeyError</span></tt></a> to <a class="reference internal" href="#AttributeError" title="AttributeError"><tt class="xref py py-exc docutils literal"><span class="pre">AttributeError</span></tt></a>, while
leaving the old exception available in <tt class="xref py py-attr docutils literal"><span class="pre">__context__</span></tt> for introspection
when debugging.</p>
<p>The default traceback display code shows these chained exceptions in
addition to the traceback for the exception itself. An explicitly chained
exception in <tt class="xref py py-attr docutils literal"><span class="pre">__cause__</span></tt> is always shown when present. An implicitly
chained exception in <tt class="xref py py-attr docutils literal"><span class="pre">__context__</span></tt> is shown only if <tt class="xref py py-attr docutils literal"><span class="pre">__cause__</span></tt>
is <a class="reference internal" href="constants.html#None" title="None"><tt class="xref py py-const docutils literal"><span class="pre">None</span></tt></a> and <tt class="xref py py-attr docutils literal"><span class="pre">__suppress_context__</span></tt> is false.</p>
<p>In either case, the exception itself is always shown after any chained
exceptions so that the final line of the traceback always shows the last
exception that was raised.</p>
<div class="section" id="base-classes">
<h2>5.1. Base classes<a class="headerlink" href="#base-classes" title="Permalink to this headline">¶</a></h2>
<p>The following exceptions are used mostly as base classes for other exceptions.</p>
<dl class="exception">
<dt id="BaseException">
<em class="property">exception </em><tt class="descname">BaseException</tt><a class="headerlink" href="#BaseException" title="Permalink to this definition">¶</a></dt>
<dd><p>The base class for all built-in exceptions.  It is not meant to be directly
inherited by user-defined classes (for that, use <a class="reference internal" href="#Exception" title="Exception"><tt class="xref py py-exc docutils literal"><span class="pre">Exception</span></tt></a>).  If
<a class="reference internal" href="stdtypes.html#str" title="str"><tt class="xref py py-func docutils literal"><span class="pre">str()</span></tt></a> is called on an instance of this class, the representation of
the argument(s) to the instance are returned, or the empty string when
there were no arguments.</p>
<dl class="attribute">
<dt id="BaseException.args">
<tt class="descname">args</tt><a class="headerlink" href="#BaseException.args" title="Permalink to this definition">¶</a></dt>
<dd><p>The tuple of arguments given to the exception constructor.  Some built-in
exceptions (like <a class="reference internal" href="#OSError" title="OSError"><tt class="xref py py-exc docutils literal"><span class="pre">OSError</span></tt></a>) expect a certain number of arguments and
assign a special meaning to the elements of this tuple, while others are
usually called only with a single string giving an error message.</p>
</dd></dl>

<dl class="method">
<dt id="BaseException.with_traceback">
<tt class="descname">with_traceback</tt><big>(</big><em>tb</em><big>)</big><a class="headerlink" href="#BaseException.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>This method sets <em>tb</em> as the new traceback for the exception and returns
the exception object.  It is usually used in exception handling code like
this:</p>
<div class="highlight-python3"><div class="highlight"><pre><span class="k">try</span><span class="p">:</span>
    <span class="o">...</span>
<span class="k">except</span> <span class="n">SomeException</span><span class="p">:</span>
    <span class="n">tb</span> <span class="o">=</span> <span class="n">sys</span><span class="o">.</span><span class="n">exc_info</span><span class="p">()[</span><span class="mi">2</span><span class="p">]</span>
    <span class="k">raise</span> <span class="n">OtherException</span><span class="p">(</span><span class="o">...</span><span class="p">)</span><span class="o">.</span><span class="n">with_traceback</span><span class="p">(</span><span class="n">tb</span><span class="p">)</span>
</pre></div>
</div>
</dd></dl>

</dd></dl>

<dl class="exception">
<dt id="Exception">
<em class="property">exception </em><tt class="descname">Exception</tt><a class="headerlink" href="#Exception" title="Permalink to this definition">¶</a></dt>
<dd><p>All built-in, non-system-exiting exceptions are derived from this class.  All
user-defined exceptions should also be derived from this class.</p>
</dd></dl>

<dl class="exception">
<dt id="ArithmeticError">
<em class="property">exception </em><tt class="descname">ArithmeticError</tt><a class="headerlink" href="#ArithmeticError" title="Permalink to this definition">¶</a></dt>
<dd><p>The base class for those built-in exceptions that are raised for various
arithmetic errors: <a class="reference internal" href="#OverflowError" title="OverflowError"><tt class="xref py py-exc docutils literal"><span class="pre">OverflowError</span></tt></a>, <a class="reference internal" href="#ZeroDivisionError" title="ZeroDivisionError"><tt class="xref py py-exc docutils literal"><span class="pre">ZeroDivisionError</span></tt></a>,
<a class="reference internal" href="#FloatingPointError" title="FloatingPointError"><tt class="xref py py-exc docutils literal"><span class="pre">FloatingPointError</span></tt></a>.</p>
</dd></dl>

<dl class="exception">
<dt id="BufferError">
<em class="property">exception </em><tt class="descname">BufferError</tt><a class="headerlink" href="#BufferError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when a <a class="reference internal" href="../c-api/buffer.html#bufferobjects"><em>buffer</em></a> related operation cannot be
performed.</p>
</dd></dl>

<dl class="exception">
<dt id="LookupError">
<em class="property">exception </em><tt class="descname">LookupError</tt><a class="headerlink" href="#LookupError" title="Permalink to this definition">¶</a></dt>
<dd><p>The base class for the exceptions that are raised when a key or index used on
a mapping or sequence is invalid: <a class="reference internal" href="#IndexError" title="IndexError"><tt class="xref py py-exc docutils literal"><span class="pre">IndexError</span></tt></a>, <a class="reference internal" href="#KeyError" title="KeyError"><tt class="xref py py-exc docutils literal"><span class="pre">KeyError</span></tt></a>.  This
can be raised directly by <a class="reference internal" href="codecs.html#codecs.lookup" title="codecs.lookup"><tt class="xref py py-func docutils literal"><span class="pre">codecs.lookup()</span></tt></a>.</p>
</dd></dl>

</div>
<div class="section" id="concrete-exceptions">
<h2>5.2. Concrete exceptions<a class="headerlink" href="#concrete-exceptions" title="Permalink to this headline">¶</a></h2>
<p>The following exceptions are the exceptions that are usually raised.</p>
<dl class="exception">
<dt id="AssertionError">
<em class="property">exception </em><tt class="descname">AssertionError</tt><a class="headerlink" href="#AssertionError" title="Permalink to this definition">¶</a></dt>
<dd><p id="index-2">Raised when an <a class="reference internal" href="../reference/simple_stmts.html#assert"><tt class="xref std std-keyword docutils literal"><span class="pre">assert</span></tt></a> statement fails.</p>
</dd></dl>

<dl class="exception">
<dt id="AttributeError">
<em class="property">exception </em><tt class="descname">AttributeError</tt><a class="headerlink" href="#AttributeError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when an attribute reference (see <a class="reference internal" href="../reference/expressions.html#attribute-references"><em>Attribute references</em></a>) or
assignment fails.  (When an object does not support attribute references or
attribute assignments at all, <a class="reference internal" href="#TypeError" title="TypeError"><tt class="xref py py-exc docutils literal"><span class="pre">TypeError</span></tt></a> is raised.)</p>
</dd></dl>

<dl class="exception">
<dt id="EOFError">
<em class="property">exception </em><tt class="descname">EOFError</tt><a class="headerlink" href="#EOFError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when the <a class="reference internal" href="functions.html#input" title="input"><tt class="xref py py-func docutils literal"><span class="pre">input()</span></tt></a> function hits an end-of-file condition (EOF)
without reading any data. (N.B.: the <tt class="xref py py-meth docutils literal"><span class="pre">io.IOBase.read()</span></tt> and
<a class="reference internal" href="io.html#io.IOBase.readline" title="io.IOBase.readline"><tt class="xref py py-meth docutils literal"><span class="pre">io.IOBase.readline()</span></tt></a> methods return an empty string when they hit EOF.)</p>
</dd></dl>

<dl class="exception">
<dt id="FloatingPointError">
<em class="property">exception </em><tt class="descname">FloatingPointError</tt><a class="headerlink" href="#FloatingPointError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when a floating point operation fails.  This exception is always defined,
but can only be raised when Python is configured with the
<tt class="docutils literal"><span class="pre">--with-fpectl</span></tt> option, or the <tt class="xref py py-const docutils literal"><span class="pre">WANT_SIGFPE_HANDLER</span></tt> symbol is
defined in the <tt class="file docutils literal"><span class="pre">pyconfig.h</span></tt> file.</p>
</dd></dl>

<dl class="exception">
<dt id="GeneratorExit">
<em class="property">exception </em><tt class="descname">GeneratorExit</tt><a class="headerlink" href="#GeneratorExit" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when a <a class="reference internal" href="../glossary.html#term-generator"><em class="xref std std-term">generator</em></a>&#8216;s <tt class="xref py py-meth docutils literal"><span class="pre">close()</span></tt> method is called.  It
directly inherits from <a class="reference internal" href="#BaseException" title="BaseException"><tt class="xref py py-exc docutils literal"><span class="pre">BaseException</span></tt></a> instead of <a class="reference internal" href="#Exception" title="Exception"><tt class="xref py py-exc docutils literal"><span class="pre">Exception</span></tt></a> since
it is technically not an error.</p>
</dd></dl>

<dl class="exception">
<dt id="ImportError">
<em class="property">exception </em><tt class="descname">ImportError</tt><a class="headerlink" href="#ImportError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when an <a class="reference internal" href="../reference/simple_stmts.html#import"><tt class="xref std std-keyword docutils literal"><span class="pre">import</span></tt></a> statement fails to find the module definition
or when a <tt class="docutils literal"><span class="pre">from</span> <span class="pre">...</span> <span class="pre">import</span></tt> fails to find a name that is to be imported.</p>
<p>The <tt class="xref py py-attr docutils literal"><span class="pre">name</span></tt> and <tt class="xref py py-attr docutils literal"><span class="pre">path</span></tt> attributes can be set using keyword-only
arguments to the constructor. When set they represent the name of the module
that was attempted to be imported and the path to any file which triggered
the exception, respectively.</p>
<div class="versionchanged">
<p><span class="versionmodified">Changed in version 3.3: </span>Added the <tt class="xref py py-attr docutils literal"><span class="pre">name</span></tt> and <tt class="xref py py-attr docutils literal"><span class="pre">path</span></tt> attributes.</p>
</div>
</dd></dl>

<dl class="exception">
<dt id="IndexError">
<em class="property">exception </em><tt class="descname">IndexError</tt><a class="headerlink" href="#IndexError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when a sequence subscript is out of range.  (Slice indices are
silently truncated to fall in the allowed range; if an index is not an
integer, <a class="reference internal" href="#TypeError" title="TypeError"><tt class="xref py py-exc docutils literal"><span class="pre">TypeError</span></tt></a> is raised.)</p>
</dd></dl>

<dl class="exception">
<dt id="KeyError">
<em class="property">exception </em><tt class="descname">KeyError</tt><a class="headerlink" href="#KeyError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when a mapping (dictionary) key is not found in the set of existing keys.</p>
</dd></dl>

<dl class="exception">
<dt id="KeyboardInterrupt">
<em class="property">exception </em><tt class="descname">KeyboardInterrupt</tt><a class="headerlink" href="#KeyboardInterrupt" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when the user hits the interrupt key (normally <tt class="kbd docutils literal"><span class="pre">Control-C</span></tt> or
<tt class="kbd docutils literal"><span class="pre">Delete</span></tt>).  During execution, a check for interrupts is made
regularly. The exception inherits from <a class="reference internal" href="#BaseException" title="BaseException"><tt class="xref py py-exc docutils literal"><span class="pre">BaseException</span></tt></a> so as to not be
accidentally caught by code that catches <a class="reference internal" href="#Exception" title="Exception"><tt class="xref py py-exc docutils literal"><span class="pre">Exception</span></tt></a> and thus prevent
the interpreter from exiting.</p>
</dd></dl>

<dl class="exception">
<dt id="MemoryError">
<em class="property">exception </em><tt class="descname">MemoryError</tt><a class="headerlink" href="#MemoryError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when an operation runs out of memory but the situation may still be
rescued (by deleting some objects).  The associated value is a string indicating
what kind of (internal) operation ran out of memory. Note that because of the
underlying memory management architecture (C&#8217;s <tt class="xref c c-func docutils literal"><span class="pre">malloc()</span></tt> function), the
interpreter may not always be able to completely recover from this situation; it
nevertheless raises an exception so that a stack traceback can be printed, in
case a run-away program was the cause.</p>
</dd></dl>

<dl class="exception">
<dt id="NameError">
<em class="property">exception </em><tt class="descname">NameError</tt><a class="headerlink" href="#NameError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when a local or global name is not found.  This applies only to
unqualified names.  The associated value is an error message that includes the
name that could not be found.</p>
</dd></dl>

<dl class="exception">
<dt id="NotImplementedError">
<em class="property">exception </em><tt class="descname">NotImplementedError</tt><a class="headerlink" href="#NotImplementedError" title="Permalink to this definition">¶</a></dt>
<dd><p>This exception is derived from <a class="reference internal" href="#RuntimeError" title="RuntimeError"><tt class="xref py py-exc docutils literal"><span class="pre">RuntimeError</span></tt></a>.  In user defined base
classes, abstract methods should raise this exception when they require derived
classes to override the method.</p>
</dd></dl>

<dl class="exception">
<dt id="OSError">
<em class="property">exception </em><tt class="descname">OSError</tt><a class="headerlink" href="#OSError" title="Permalink to this definition">¶</a></dt>
<dd><p id="index-3">This exception is raised when a system function returns a system-related
error, including I/O failures such as &#8220;file not found&#8221; or &#8220;disk full&#8221;
(not for illegal argument types or other incidental errors).  Often a
subclass of <a class="reference internal" href="#OSError" title="OSError"><tt class="xref py py-exc docutils literal"><span class="pre">OSError</span></tt></a> will actually be raised as described in
<a class="reference internal" href="#os-exceptions">OS exceptions</a> below.  The <a class="reference internal" href="errno.html#module-errno" title="errno: Standard errno system symbols."><tt class="xref py py-attr docutils literal"><span class="pre">errno</span></tt></a> attribute is a numeric error
code from the C variable <tt class="xref c c-data docutils literal"><span class="pre">errno</span></tt>.</p>
<p>Under Windows, the <tt class="xref py py-attr docutils literal"><span class="pre">winerror</span></tt> attribute gives you the native
Windows error code.  The <a class="reference internal" href="errno.html#module-errno" title="errno: Standard errno system symbols."><tt class="xref py py-attr docutils literal"><span class="pre">errno</span></tt></a> attribute is then an approximate
translation, in POSIX terms, of that native error code.</p>
<p>Under all platforms, the <tt class="xref py py-attr docutils literal"><span class="pre">strerror</span></tt> attribute is the corresponding
error message as provided by the operating system (as formatted by the C
functions <tt class="xref c c-func docutils literal"><span class="pre">perror()</span></tt> under POSIX, and <tt class="xref c c-func docutils literal"><span class="pre">FormatMessage()</span></tt>
Windows).</p>
<p>For exceptions that involve a file system path (such as <a class="reference internal" href="functions.html#open" title="open"><tt class="xref py py-func docutils literal"><span class="pre">open()</span></tt></a> or
<a class="reference internal" href="os.html#os.unlink" title="os.unlink"><tt class="xref py py-func docutils literal"><span class="pre">os.unlink()</span></tt></a>), the exception instance will contain an additional
attribute, <tt class="xref py py-attr docutils literal"><span class="pre">filename</span></tt>, which is the file name passed to the function.
For functions that involve two file system paths (such as
<a class="reference internal" href="os.html#os.rename" title="os.rename"><tt class="xref py py-func docutils literal"><span class="pre">os.rename()</span></tt></a>), the exception instance will contain a second
<tt class="xref py py-attr docutils literal"><span class="pre">filename2</span></tt> attribute corresponding to the second file name passed
to the function.</p>
<div class="versionchanged">
<p><span class="versionmodified">Changed in version 3.3: </span><a class="reference internal" href="#EnvironmentError" title="EnvironmentError"><tt class="xref py py-exc docutils literal"><span class="pre">EnvironmentError</span></tt></a>, <a class="reference internal" href="#IOError" title="IOError"><tt class="xref py py-exc docutils literal"><span class="pre">IOError</span></tt></a>, <a class="reference internal" href="#WindowsError" title="WindowsError"><tt class="xref py py-exc docutils literal"><span class="pre">WindowsError</span></tt></a>,
<tt class="xref py py-exc docutils literal"><span class="pre">VMSError</span></tt>, <a class="reference internal" href="socket.html#socket.error" title="socket.error"><tt class="xref py py-exc docutils literal"><span class="pre">socket.error</span></tt></a>, <a class="reference internal" href="select.html#select.error" title="select.error"><tt class="xref py py-exc docutils literal"><span class="pre">select.error</span></tt></a> and
<tt class="xref py py-exc docutils literal"><span class="pre">mmap.error</span></tt> have been merged into <a class="reference internal" href="#OSError" title="OSError"><tt class="xref py py-exc docutils literal"><span class="pre">OSError</span></tt></a>.</p>
</div>
<div class="versionchanged">
<p><span class="versionmodified">Changed in version 3.4: </span>The <tt class="xref py py-attr docutils literal"><span class="pre">filename</span></tt> attribute is now the original file name passed to
the function, instead of the name encoded to or decoded from the
filesystem encoding.  Also, the <tt class="xref py py-attr docutils literal"><span class="pre">filename2</span></tt> attribute was added.</p>
</div>
</dd></dl>

<dl class="exception">
<dt id="OverflowError">
<em class="property">exception </em><tt class="descname">OverflowError</tt><a class="headerlink" href="#OverflowError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when the result of an arithmetic operation is too large to be
represented.  This cannot occur for integers (which would rather raise
<a class="reference internal" href="#MemoryError" title="MemoryError"><tt class="xref py py-exc docutils literal"><span class="pre">MemoryError</span></tt></a> than give up).  However, for historical reasons,
OverflowError is sometimes raised for integers that are outside a required
range.   Because of the lack of standardization of floating point exception
handling in C, most floating point operations are not checked.</p>
</dd></dl>

<dl class="exception">
<dt id="ReferenceError">
<em class="property">exception </em><tt class="descname">ReferenceError</tt><a class="headerlink" href="#ReferenceError" title="Permalink to this definition">¶</a></dt>
<dd><p>This exception is raised when a weak reference proxy, created by the
<a class="reference internal" href="weakref.html#weakref.proxy" title="weakref.proxy"><tt class="xref py py-func docutils literal"><span class="pre">weakref.proxy()</span></tt></a> function, is used to access an attribute of the referent
after it has been garbage collected. For more information on weak references,
see the <a class="reference internal" href="weakref.html#module-weakref" title="weakref: Support for weak references and weak dictionaries."><tt class="xref py py-mod docutils literal"><span class="pre">weakref</span></tt></a> module.</p>
</dd></dl>

<dl class="exception">
<dt id="RuntimeError">
<em class="property">exception </em><tt class="descname">RuntimeError</tt><a class="headerlink" href="#RuntimeError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when an error is detected that doesn&#8217;t fall in any of the other
categories.  The associated value is a string indicating what precisely went
wrong.</p>
</dd></dl>

<dl class="exception">
<dt id="StopIteration">
<em class="property">exception </em><tt class="descname">StopIteration</tt><a class="headerlink" href="#StopIteration" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised by built-in function <a class="reference internal" href="functions.html#next" title="next"><tt class="xref py py-func docutils literal"><span class="pre">next()</span></tt></a> and an <a class="reference internal" href="../glossary.html#term-iterator"><em class="xref std std-term">iterator</em></a>&#8216;s
<a class="reference internal" href="stdtypes.html#iterator.__next__" title="iterator.__next__"><tt class="xref py py-meth docutils literal"><span class="pre">__next__()</span></tt></a> method to signal that there are no further
items produced by the iterator.</p>
<p>The exception object has a single attribute <tt class="xref py py-attr docutils literal"><span class="pre">value</span></tt>, which is
given as an argument when constructing the exception, and defaults
to <a class="reference internal" href="constants.html#None" title="None"><tt class="xref py py-const docutils literal"><span class="pre">None</span></tt></a>.</p>
<p>When a generator function returns, a new <a class="reference internal" href="#StopIteration" title="StopIteration"><tt class="xref py py-exc docutils literal"><span class="pre">StopIteration</span></tt></a> instance is
raised, and the value returned by the function is used as the
<tt class="xref py py-attr docutils literal"><span class="pre">value</span></tt> parameter to the constructor of the exception.</p>
<div class="versionchanged">
<p><span class="versionmodified">Changed in version 3.3: </span>Added <tt class="docutils literal"><span class="pre">value</span></tt> attribute and the ability for generator functions to
use it to return a value.</p>
</div>
</dd></dl>

<dl class="exception">
<dt id="SyntaxError">
<em class="property">exception </em><tt class="descname">SyntaxError</tt><a class="headerlink" href="#SyntaxError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when the parser encounters a syntax error.  This may occur in an
<a class="reference internal" href="../reference/simple_stmts.html#import"><tt class="xref std std-keyword docutils literal"><span class="pre">import</span></tt></a> statement, in a call to the built-in functions <a class="reference internal" href="functions.html#exec" title="exec"><tt class="xref py py-func docutils literal"><span class="pre">exec()</span></tt></a>
or <a class="reference internal" href="functions.html#eval" title="eval"><tt class="xref py py-func docutils literal"><span class="pre">eval()</span></tt></a>, or when reading the initial script or standard input
(also interactively).</p>
<p>Instances of this class have attributes <tt class="xref py py-attr docutils literal"><span class="pre">filename</span></tt>, <tt class="xref py py-attr docutils literal"><span class="pre">lineno</span></tt>,
<tt class="xref py py-attr docutils literal"><span class="pre">offset</span></tt> and <tt class="xref py py-attr docutils literal"><span class="pre">text</span></tt> for easier access to the details.  <a class="reference internal" href="stdtypes.html#str" title="str"><tt class="xref py py-func docutils literal"><span class="pre">str()</span></tt></a>
of the exception instance returns only the message.</p>
</dd></dl>

<dl class="exception">
<dt id="IndentationError">
<em class="property">exception </em><tt class="descname">IndentationError</tt><a class="headerlink" href="#IndentationError" title="Permalink to this definition">¶</a></dt>
<dd><p>Base class for syntax errors related to incorrect indentation.  This is a
subclass of <a class="reference internal" href="#SyntaxError" title="SyntaxError"><tt class="xref py py-exc docutils literal"><span class="pre">SyntaxError</span></tt></a>.</p>
</dd></dl>

<dl class="exception">
<dt id="TabError">
<em class="property">exception </em><tt class="descname">TabError</tt><a class="headerlink" href="#TabError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when indentation contains an inconsistent use of tabs and spaces.
This is a subclass of <a class="reference internal" href="#IndentationError" title="IndentationError"><tt class="xref py py-exc docutils literal"><span class="pre">IndentationError</span></tt></a>.</p>
</dd></dl>

<dl class="exception">
<dt id="SystemError">
<em class="property">exception </em><tt class="descname">SystemError</tt><a class="headerlink" href="#SystemError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when the interpreter finds an internal error, but the situation does not
look so serious to cause it to abandon all hope. The associated value is a
string indicating what went wrong (in low-level terms).</p>
<p>You should report this to the author or maintainer of your Python interpreter.
Be sure to report the version of the Python interpreter (<tt class="docutils literal"><span class="pre">sys.version</span></tt>; it is
also printed at the start of an interactive Python session), the exact error
message (the exception&#8217;s associated value) and if possible the source of the
program that triggered the error.</p>
</dd></dl>

<dl class="exception">
<dt id="SystemExit">
<em class="property">exception </em><tt class="descname">SystemExit</tt><a class="headerlink" href="#SystemExit" title="Permalink to this definition">¶</a></dt>
<dd><p>This exception is raised by the <a class="reference internal" href="sys.html#sys.exit" title="sys.exit"><tt class="xref py py-func docutils literal"><span class="pre">sys.exit()</span></tt></a> function.  It inherits from
<a class="reference internal" href="#BaseException" title="BaseException"><tt class="xref py py-exc docutils literal"><span class="pre">BaseException</span></tt></a> instead of <a class="reference internal" href="#Exception" title="Exception"><tt class="xref py py-exc docutils literal"><span class="pre">Exception</span></tt></a> so that it is not accidentally
caught by code that catches <a class="reference internal" href="#Exception" title="Exception"><tt class="xref py py-exc docutils literal"><span class="pre">Exception</span></tt></a>.  This allows the exception to
properly propagate up and cause the interpreter to exit.  When it is not
handled, the Python interpreter exits; no stack traceback is printed.  The
constructor accepts the same optional argument passed to <a class="reference internal" href="sys.html#sys.exit" title="sys.exit"><tt class="xref py py-func docutils literal"><span class="pre">sys.exit()</span></tt></a>.
If the value is an integer, it specifies the system exit status (passed to
C&#8217;s <tt class="xref c c-func docutils literal"><span class="pre">exit()</span></tt> function); if it is <tt class="docutils literal"><span class="pre">None</span></tt>, the exit status is zero; if
it has another type (such as a string), the object&#8217;s value is printed and
the exit status is one.</p>
<p>A call to <a class="reference internal" href="sys.html#sys.exit" title="sys.exit"><tt class="xref py py-func docutils literal"><span class="pre">sys.exit()</span></tt></a> is translated into an exception so that clean-up
handlers (<a class="reference internal" href="../reference/compound_stmts.html#finally"><tt class="xref std std-keyword docutils literal"><span class="pre">finally</span></tt></a> clauses of <a class="reference internal" href="../reference/compound_stmts.html#try"><tt class="xref std std-keyword docutils literal"><span class="pre">try</span></tt></a> statements) can be
executed, and so that a debugger can execute a script without running the risk
of losing control.  The <a class="reference internal" href="os.html#os._exit" title="os._exit"><tt class="xref py py-func docutils literal"><span class="pre">os._exit()</span></tt></a> function can be used if it is
absolutely positively necessary to exit immediately (for example, in the child
process after a call to <a class="reference internal" href="os.html#os.fork" title="os.fork"><tt class="xref py py-func docutils literal"><span class="pre">os.fork()</span></tt></a>).</p>
<dl class="attribute">
<dt id="SystemExit.code">
<tt class="descname">code</tt><a class="headerlink" href="#SystemExit.code" title="Permalink to this definition">¶</a></dt>
<dd><p>The exit status or error message that is passed to the constructor.
(Defaults to <tt class="docutils literal"><span class="pre">None</span></tt>.)</p>
</dd></dl>

</dd></dl>

<dl class="exception">
<dt id="TypeError">
<em class="property">exception </em><tt class="descname">TypeError</tt><a class="headerlink" href="#TypeError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when an operation or function is applied to an object of inappropriate
type.  The associated value is a string giving details about the type mismatch.</p>
</dd></dl>

<dl class="exception">
<dt id="UnboundLocalError">
<em class="property">exception </em><tt class="descname">UnboundLocalError</tt><a class="headerlink" href="#UnboundLocalError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when a reference is made to a local variable in a function or method, but
no value has been bound to that variable.  This is a subclass of
<a class="reference internal" href="#NameError" title="NameError"><tt class="xref py py-exc docutils literal"><span class="pre">NameError</span></tt></a>.</p>
</dd></dl>

<dl class="exception">
<dt id="UnicodeError">
<em class="property">exception </em><tt class="descname">UnicodeError</tt><a class="headerlink" href="#UnicodeError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when a Unicode-related encoding or decoding error occurs.  It is a
subclass of <a class="reference internal" href="#ValueError" title="ValueError"><tt class="xref py py-exc docutils literal"><span class="pre">ValueError</span></tt></a>.</p>
<p><a class="reference internal" href="#UnicodeError" title="UnicodeError"><tt class="xref py py-exc docutils literal"><span class="pre">UnicodeError</span></tt></a> has attributes that describe the encoding or decoding
error.  For example, <tt class="docutils literal"><span class="pre">err.object[err.start:err.end]</span></tt> gives the particular
invalid input that the codec failed on.</p>
<dl class="attribute">
<dt id="UnicodeError.encoding">
<tt class="descname">encoding</tt><a class="headerlink" href="#UnicodeError.encoding" title="Permalink to this definition">¶</a></dt>
<dd><p>The name of the encoding that raised the error.</p>
</dd></dl>

<dl class="attribute">
<dt id="UnicodeError.reason">
<tt class="descname">reason</tt><a class="headerlink" href="#UnicodeError.reason" title="Permalink to this definition">¶</a></dt>
<dd><p>A string describing the specific codec error.</p>
</dd></dl>

<dl class="attribute">
<dt id="UnicodeError.object">
<tt class="descname">object</tt><a class="headerlink" href="#UnicodeError.object" title="Permalink to this definition">¶</a></dt>
<dd><p>The object the codec was attempting to encode or decode.</p>
</dd></dl>

<dl class="attribute">
<dt id="UnicodeError.start">
<tt class="descname">start</tt><a class="headerlink" href="#UnicodeError.start" title="Permalink to this definition">¶</a></dt>
<dd><p>The first index of invalid data in <a class="reference internal" href="functions.html#object" title="object"><tt class="xref py py-attr docutils literal"><span class="pre">object</span></tt></a>.</p>
</dd></dl>

<dl class="attribute">
<dt id="UnicodeError.end">
<tt class="descname">end</tt><a class="headerlink" href="#UnicodeError.end" title="Permalink to this definition">¶</a></dt>
<dd><p>The index after the last invalid data in <a class="reference internal" href="functions.html#object" title="object"><tt class="xref py py-attr docutils literal"><span class="pre">object</span></tt></a>.</p>
</dd></dl>

</dd></dl>

<dl class="exception">
<dt id="UnicodeEncodeError">
<em class="property">exception </em><tt class="descname">UnicodeEncodeError</tt><a class="headerlink" href="#UnicodeEncodeError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when a Unicode-related error occurs during encoding.  It is a subclass of
<a class="reference internal" href="#UnicodeError" title="UnicodeError"><tt class="xref py py-exc docutils literal"><span class="pre">UnicodeError</span></tt></a>.</p>
</dd></dl>

<dl class="exception">
<dt id="UnicodeDecodeError">
<em class="property">exception </em><tt class="descname">UnicodeDecodeError</tt><a class="headerlink" href="#UnicodeDecodeError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when a Unicode-related error occurs during decoding.  It is a subclass of
<a class="reference internal" href="#UnicodeError" title="UnicodeError"><tt class="xref py py-exc docutils literal"><span class="pre">UnicodeError</span></tt></a>.</p>
</dd></dl>

<dl class="exception">
<dt id="UnicodeTranslateError">
<em class="property">exception </em><tt class="descname">UnicodeTranslateError</tt><a class="headerlink" href="#UnicodeTranslateError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when a Unicode-related error occurs during translating.  It is a subclass
of <a class="reference internal" href="#UnicodeError" title="UnicodeError"><tt class="xref py py-exc docutils literal"><span class="pre">UnicodeError</span></tt></a>.</p>
</dd></dl>

<dl class="exception">
<dt id="ValueError">
<em class="property">exception </em><tt class="descname">ValueError</tt><a class="headerlink" href="#ValueError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when a built-in operation or function receives an argument that has the
right type but an inappropriate value, and the situation is not described by a
more precise exception such as <a class="reference internal" href="#IndexError" title="IndexError"><tt class="xref py py-exc docutils literal"><span class="pre">IndexError</span></tt></a>.</p>
</dd></dl>

<dl class="exception">
<dt id="ZeroDivisionError">
<em class="property">exception </em><tt class="descname">ZeroDivisionError</tt><a class="headerlink" href="#ZeroDivisionError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when the second argument of a division or modulo operation is zero.  The
associated value is a string indicating the type of the operands and the
operation.</p>
</dd></dl>

<p>The following exceptions are kept for compatibility with previous versions;
starting from Python 3.3, they are aliases of <a class="reference internal" href="#OSError" title="OSError"><tt class="xref py py-exc docutils literal"><span class="pre">OSError</span></tt></a>.</p>
<dl class="exception">
<dt id="EnvironmentError">
<em class="property">exception </em><tt class="descname">EnvironmentError</tt><a class="headerlink" href="#EnvironmentError" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="exception">
<dt id="IOError">
<em class="property">exception </em><tt class="descname">IOError</tt><a class="headerlink" href="#IOError" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="exception">
<dt id="WindowsError">
<em class="property">exception </em><tt class="descname">WindowsError</tt><a class="headerlink" href="#WindowsError" title="Permalink to this definition">¶</a></dt>
<dd><p>Only available on Windows.</p>
</dd></dl>

<div class="section" id="os-exceptions">
<h3>5.2.1. OS exceptions<a class="headerlink" href="#os-exceptions" title="Permalink to this headline">¶</a></h3>
<p>The following exceptions are subclasses of <a class="reference internal" href="#OSError" title="OSError"><tt class="xref py py-exc docutils literal"><span class="pre">OSError</span></tt></a>, they get raised
depending on the system error code.</p>
<dl class="exception">
<dt id="BlockingIOError">
<em class="property">exception </em><tt class="descname">BlockingIOError</tt><a class="headerlink" href="#BlockingIOError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when an operation would block on an object (e.g. socket) set
for non-blocking operation.
Corresponds to <tt class="xref c c-data docutils literal"><span class="pre">errno</span></tt> <tt class="docutils literal"><span class="pre">EAGAIN</span></tt>, <tt class="docutils literal"><span class="pre">EALREADY</span></tt>,
<tt class="docutils literal"><span class="pre">EWOULDBLOCK</span></tt> and <tt class="docutils literal"><span class="pre">EINPROGRESS</span></tt>.</p>
<p>In addition to those of <a class="reference internal" href="#OSError" title="OSError"><tt class="xref py py-exc docutils literal"><span class="pre">OSError</span></tt></a>, <a class="reference internal" href="#BlockingIOError" title="BlockingIOError"><tt class="xref py py-exc docutils literal"><span class="pre">BlockingIOError</span></tt></a> can have
one more attribute:</p>
<dl class="attribute">
<dt id="BlockingIOError.characters_written">
<tt class="descname">characters_written</tt><a class="headerlink" href="#BlockingIOError.characters_written" title="Permalink to this definition">¶</a></dt>
<dd><p>An integer containing the number of characters written to the stream
before it blocked.  This attribute is available when using the
buffered I/O classes from the <a class="reference internal" href="io.html#module-io" title="io: Core tools for working with streams."><tt class="xref py py-mod docutils literal"><span class="pre">io</span></tt></a> module.</p>
</dd></dl>

</dd></dl>

<dl class="exception">
<dt id="ChildProcessError">
<em class="property">exception </em><tt class="descname">ChildProcessError</tt><a class="headerlink" href="#ChildProcessError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when an operation on a child process failed.
Corresponds to <tt class="xref c c-data docutils literal"><span class="pre">errno</span></tt> <tt class="docutils literal"><span class="pre">ECHILD</span></tt>.</p>
</dd></dl>

<dl class="exception">
<dt id="ConnectionError">
<em class="property">exception </em><tt class="descname">ConnectionError</tt><a class="headerlink" href="#ConnectionError" title="Permalink to this definition">¶</a></dt>
<dd><p>A base class for connection-related issues.</p>
<p>Subclasses are <a class="reference internal" href="#BrokenPipeError" title="BrokenPipeError"><tt class="xref py py-exc docutils literal"><span class="pre">BrokenPipeError</span></tt></a>, <a class="reference internal" href="#ConnectionAbortedError" title="ConnectionAbortedError"><tt class="xref py py-exc docutils literal"><span class="pre">ConnectionAbortedError</span></tt></a>,
<a class="reference internal" href="#ConnectionRefusedError" title="ConnectionRefusedError"><tt class="xref py py-exc docutils literal"><span class="pre">ConnectionRefusedError</span></tt></a> and <a class="reference internal" href="#ConnectionResetError" title="ConnectionResetError"><tt class="xref py py-exc docutils literal"><span class="pre">ConnectionResetError</span></tt></a>.</p>
</dd></dl>

<dl class="exception">
<dt id="BrokenPipeError">
<em class="property">exception </em><tt class="descname">BrokenPipeError</tt><a class="headerlink" href="#BrokenPipeError" title="Permalink to this definition">¶</a></dt>
<dd><p>A subclass of <a class="reference internal" href="#ConnectionError" title="ConnectionError"><tt class="xref py py-exc docutils literal"><span class="pre">ConnectionError</span></tt></a>, raised when trying to write on a
pipe while the other end has been closed, or trying to write on a socket
which has been shutdown for writing.
Corresponds to <tt class="xref c c-data docutils literal"><span class="pre">errno</span></tt> <tt class="docutils literal"><span class="pre">EPIPE</span></tt> and <tt class="docutils literal"><span class="pre">ESHUTDOWN</span></tt>.</p>
</dd></dl>

<dl class="exception">
<dt id="ConnectionAbortedError">
<em class="property">exception </em><tt class="descname">ConnectionAbortedError</tt><a class="headerlink" href="#ConnectionAbortedError" title="Permalink to this definition">¶</a></dt>
<dd><p>A subclass of <a class="reference internal" href="#ConnectionError" title="ConnectionError"><tt class="xref py py-exc docutils literal"><span class="pre">ConnectionError</span></tt></a>, raised when a connection attempt
is aborted by the peer.
Corresponds to <tt class="xref c c-data docutils literal"><span class="pre">errno</span></tt> <tt class="docutils literal"><span class="pre">ECONNABORTED</span></tt>.</p>
</dd></dl>

<dl class="exception">
<dt id="ConnectionRefusedError">
<em class="property">exception </em><tt class="descname">ConnectionRefusedError</tt><a class="headerlink" href="#ConnectionRefusedError" title="Permalink to this definition">¶</a></dt>
<dd><p>A subclass of <a class="reference internal" href="#ConnectionError" title="ConnectionError"><tt class="xref py py-exc docutils literal"><span class="pre">ConnectionError</span></tt></a>, raised when a connection attempt
is refused by the peer.
Corresponds to <tt class="xref c c-data docutils literal"><span class="pre">errno</span></tt> <tt class="docutils literal"><span class="pre">ECONNREFUSED</span></tt>.</p>
</dd></dl>

<dl class="exception">
<dt id="ConnectionResetError">
<em class="property">exception </em><tt class="descname">ConnectionResetError</tt><a class="headerlink" href="#ConnectionResetError" title="Permalink to this definition">¶</a></dt>
<dd><p>A subclass of <a class="reference internal" href="#ConnectionError" title="ConnectionError"><tt class="xref py py-exc docutils literal"><span class="pre">ConnectionError</span></tt></a>, raised when a connection is
reset by the peer.
Corresponds to <tt class="xref c c-data docutils literal"><span class="pre">errno</span></tt> <tt class="docutils literal"><span class="pre">ECONNRESET</span></tt>.</p>
</dd></dl>

<dl class="exception">
<dt id="FileExistsError">
<em class="property">exception </em><tt class="descname">FileExistsError</tt><a class="headerlink" href="#FileExistsError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when trying to create a file or directory which already exists.
Corresponds to <tt class="xref c c-data docutils literal"><span class="pre">errno</span></tt> <tt class="docutils literal"><span class="pre">EEXIST</span></tt>.</p>
</dd></dl>

<dl class="exception">
<dt id="FileNotFoundError">
<em class="property">exception </em><tt class="descname">FileNotFoundError</tt><a class="headerlink" href="#FileNotFoundError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when a file or directory is requested but doesn&#8217;t exist.
Corresponds to <tt class="xref c c-data docutils literal"><span class="pre">errno</span></tt> <tt class="docutils literal"><span class="pre">ENOENT</span></tt>.</p>
</dd></dl>

<dl class="exception">
<dt id="InterruptedError">
<em class="property">exception </em><tt class="descname">InterruptedError</tt><a class="headerlink" href="#InterruptedError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when a system call is interrupted by an incoming signal.
Corresponds to <tt class="xref c c-data docutils literal"><span class="pre">errno</span></tt> <tt class="docutils literal"><span class="pre">EINTR</span></tt>.</p>
</dd></dl>

<dl class="exception">
<dt id="IsADirectoryError">
<em class="property">exception </em><tt class="descname">IsADirectoryError</tt><a class="headerlink" href="#IsADirectoryError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when a file operation (such as <a class="reference internal" href="os.html#os.remove" title="os.remove"><tt class="xref py py-func docutils literal"><span class="pre">os.remove()</span></tt></a>) is requested
on a directory.
Corresponds to <tt class="xref c c-data docutils literal"><span class="pre">errno</span></tt> <tt class="docutils literal"><span class="pre">EISDIR</span></tt>.</p>
</dd></dl>

<dl class="exception">
<dt id="NotADirectoryError">
<em class="property">exception </em><tt class="descname">NotADirectoryError</tt><a class="headerlink" href="#NotADirectoryError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when a directory operation (such as <a class="reference internal" href="os.html#os.listdir" title="os.listdir"><tt class="xref py py-func docutils literal"><span class="pre">os.listdir()</span></tt></a>) is requested
on something which is not a directory.
Corresponds to <tt class="xref c c-data docutils literal"><span class="pre">errno</span></tt> <tt class="docutils literal"><span class="pre">ENOTDIR</span></tt>.</p>
</dd></dl>

<dl class="exception">
<dt id="PermissionError">
<em class="property">exception </em><tt class="descname">PermissionError</tt><a class="headerlink" href="#PermissionError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when trying to run an operation without the adequate access
rights - for example filesystem permissions.
Corresponds to <tt class="xref c c-data docutils literal"><span class="pre">errno</span></tt> <tt class="docutils literal"><span class="pre">EACCES</span></tt> and <tt class="docutils literal"><span class="pre">EPERM</span></tt>.</p>
</dd></dl>

<dl class="exception">
<dt id="ProcessLookupError">
<em class="property">exception </em><tt class="descname">ProcessLookupError</tt><a class="headerlink" href="#ProcessLookupError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when a given process doesn&#8217;t exist.
Corresponds to <tt class="xref c c-data docutils literal"><span class="pre">errno</span></tt> <tt class="docutils literal"><span class="pre">ESRCH</span></tt>.</p>
</dd></dl>

<dl class="exception">
<dt id="TimeoutError">
<em class="property">exception </em><tt class="descname">TimeoutError</tt><a class="headerlink" href="#TimeoutError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when a system function timed out at the system level.
Corresponds to <tt class="xref c c-data docutils literal"><span class="pre">errno</span></tt> <tt class="docutils literal"><span class="pre">ETIMEDOUT</span></tt>.</p>
</dd></dl>

<div class="versionadded">
<p><span class="versionmodified">New in version 3.3: </span>All the above <a class="reference internal" href="#OSError" title="OSError"><tt class="xref py py-exc docutils literal"><span class="pre">OSError</span></tt></a> subclasses were added.</p>
</div>
<div class="admonition seealso">
<p class="first admonition-title">See also</p>
<p class="last"><span class="target" id="index-4"></span><a class="pep reference external" href="http://www.python.org/dev/peps/pep-3151"><strong>PEP 3151</strong></a> - Reworking the OS and IO exception hierarchy</p>
</div>
</div>
</div>
<div class="section" id="warnings">
<h2>5.3. Warnings<a class="headerlink" href="#warnings" title="Permalink to this headline">¶</a></h2>
<p>The following exceptions are used as warning categories; see the <a class="reference internal" href="warnings.html#module-warnings" title="warnings: Issue warning messages and control their disposition."><tt class="xref py py-mod docutils literal"><span class="pre">warnings</span></tt></a>
module for more information.</p>
<dl class="exception">
<dt id="Warning">
<em class="property">exception </em><tt class="descname">Warning</tt><a class="headerlink" href="#Warning" title="Permalink to this definition">¶</a></dt>
<dd><p>Base class for warning categories.</p>
</dd></dl>

<dl class="exception">
<dt id="UserWarning">
<em class="property">exception </em><tt class="descname">UserWarning</tt><a class="headerlink" href="#UserWarning" title="Permalink to this definition">¶</a></dt>
<dd><p>Base class for warnings generated by user code.</p>
</dd></dl>

<dl class="exception">
<dt id="DeprecationWarning">
<em class="property">exception </em><tt class="descname">DeprecationWarning</tt><a class="headerlink" href="#DeprecationWarning" title="Permalink to this definition">¶</a></dt>
<dd><p>Base class for warnings about deprecated features.</p>
</dd></dl>

<dl class="exception">
<dt id="PendingDeprecationWarning">
<em class="property">exception </em><tt class="descname">PendingDeprecationWarning</tt><a class="headerlink" href="#PendingDeprecationWarning" title="Permalink to this definition">¶</a></dt>
<dd><p>Base class for warnings about features which will be deprecated in the future.</p>
</dd></dl>

<dl class="exception">
<dt id="SyntaxWarning">
<em class="property">exception </em><tt class="descname">SyntaxWarning</tt><a class="headerlink" href="#SyntaxWarning" title="Permalink to this definition">¶</a></dt>
<dd><p>Base class for warnings about dubious syntax</p>
</dd></dl>

<dl class="exception">
<dt id="RuntimeWarning">
<em class="property">exception </em><tt class="descname">RuntimeWarning</tt><a class="headerlink" href="#RuntimeWarning" title="Permalink to this definition">¶</a></dt>
<dd><p>Base class for warnings about dubious runtime behavior.</p>
</dd></dl>

<dl class="exception">
<dt id="FutureWarning">
<em class="property">exception </em><tt class="descname">FutureWarning</tt><a class="headerlink" href="#FutureWarning" title="Permalink to this definition">¶</a></dt>
<dd><p>Base class for warnings about constructs that will change semantically in the
future.</p>
</dd></dl>

<dl class="exception">
<dt id="ImportWarning">
<em class="property">exception </em><tt class="descname">ImportWarning</tt><a class="headerlink" href="#ImportWarning" title="Permalink to this definition">¶</a></dt>
<dd><p>Base class for warnings about probable mistakes in module imports.</p>
</dd></dl>

<dl class="exception">
<dt id="UnicodeWarning">
<em class="property">exception </em><tt class="descname">UnicodeWarning</tt><a class="headerlink" href="#UnicodeWarning" title="Permalink to this definition">¶</a></dt>
<dd><p>Base class for warnings related to Unicode.</p>
</dd></dl>

<dl class="exception">
<dt id="BytesWarning">
<em class="property">exception </em><tt class="descname">BytesWarning</tt><a class="headerlink" href="#BytesWarning" title="Permalink to this definition">¶</a></dt>
<dd><p>Base class for warnings related to <a class="reference internal" href="functions.html#bytes" title="bytes"><tt class="xref py py-class docutils literal"><span class="pre">bytes</span></tt></a> and <a class="reference internal" href="functions.html#bytearray" title="bytearray"><tt class="xref py py-class docutils literal"><span class="pre">bytearray</span></tt></a>.</p>
</dd></dl>

<dl class="exception">
<dt id="ResourceWarning">
<em class="property">exception </em><tt class="descname">ResourceWarning</tt><a class="headerlink" href="#ResourceWarning" title="Permalink to this definition">¶</a></dt>
<dd><p>Base class for warnings related to resource usage.</p>
<div class="versionadded">
<p><span class="versionmodified">New in version 3.2.</span></p>
</div>
</dd></dl>

</div>
<div class="section" id="exception-hierarchy">
<h2>5.4. Exception hierarchy<a class="headerlink" href="#exception-hierarchy" title="Permalink to this headline">¶</a></h2>
<p>The class hierarchy for built-in exceptions is:</p>
<div class="highlight-python3"><div class="highlight"><pre><span class="ne">BaseException</span>
 <span class="o">+--</span> <span class="ne">SystemExit</span>
 <span class="o">+--</span> <span class="ne">KeyboardInterrupt</span>
 <span class="o">+--</span> <span class="ne">GeneratorExit</span>
 <span class="o">+--</span> <span class="ne">Exception</span>
      <span class="o">+--</span> <span class="ne">StopIteration</span>
      <span class="o">+--</span> <span class="ne">ArithmeticError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">FloatingPointError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">OverflowError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">ZeroDivisionError</span>
      <span class="o">+--</span> <span class="ne">AssertionError</span>
      <span class="o">+--</span> <span class="ne">AttributeError</span>
      <span class="o">+--</span> <span class="ne">BufferError</span>
      <span class="o">+--</span> <span class="ne">EOFError</span>
      <span class="o">+--</span> <span class="ne">ImportError</span>
      <span class="o">+--</span> <span class="ne">LookupError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">IndexError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">KeyError</span>
      <span class="o">+--</span> <span class="ne">MemoryError</span>
      <span class="o">+--</span> <span class="ne">NameError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">UnboundLocalError</span>
      <span class="o">+--</span> <span class="ne">OSError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">BlockingIOError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">ChildProcessError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">ConnectionError</span>
      <span class="o">|</span>    <span class="o">|</span>    <span class="o">+--</span> <span class="ne">BrokenPipeError</span>
      <span class="o">|</span>    <span class="o">|</span>    <span class="o">+--</span> <span class="ne">ConnectionAbortedError</span>
      <span class="o">|</span>    <span class="o">|</span>    <span class="o">+--</span> <span class="ne">ConnectionRefusedError</span>
      <span class="o">|</span>    <span class="o">|</span>    <span class="o">+--</span> <span class="ne">ConnectionResetError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">FileExistsError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">FileNotFoundError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">InterruptedError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">IsADirectoryError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">NotADirectoryError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">PermissionError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">ProcessLookupError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">TimeoutError</span>
      <span class="o">+--</span> <span class="ne">ReferenceError</span>
      <span class="o">+--</span> <span class="ne">RuntimeError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">NotImplementedError</span>
      <span class="o">+--</span> <span class="ne">SyntaxError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">IndentationError</span>
      <span class="o">|</span>         <span class="o">+--</span> <span class="ne">TabError</span>
      <span class="o">+--</span> <span class="ne">SystemError</span>
      <span class="o">+--</span> <span class="ne">TypeError</span>
      <span class="o">+--</span> <span class="ne">ValueError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">UnicodeError</span>
      <span class="o">|</span>         <span class="o">+--</span> <span class="ne">UnicodeDecodeError</span>
      <span class="o">|</span>         <span class="o">+--</span> <span class="ne">UnicodeEncodeError</span>
      <span class="o">|</span>         <span class="o">+--</span> <span class="ne">UnicodeTranslateError</span>
      <span class="o">+--</span> <span class="ne">Warning</span>
           <span class="o">+--</span> <span class="ne">DeprecationWarning</span>
           <span class="o">+--</span> <span class="ne">PendingDeprecationWarning</span>
           <span class="o">+--</span> <span class="ne">RuntimeWarning</span>
           <span class="o">+--</span> <span class="ne">SyntaxWarning</span>
           <span class="o">+--</span> <span class="ne">UserWarning</span>
           <span class="o">+--</span> <span class="ne">FutureWarning</span>
           <span class="o">+--</span> <span class="ne">ImportWarning</span>
           <span class="o">+--</span> <span class="ne">UnicodeWarning</span>
           <span class="o">+--</span> <span class="ne">BytesWarning</span>
           <span class="o">+--</span> <span class="n">ResourceWarning</span>
</pre></div>
</div>
</div>
</div>


          </div>
        </div>
      </div>
      <div class="sphinxsidebar">
        <div class="sphinxsidebarwrapper">
  <h3><a href="../contents.html">Table Of Contents</a></h3>
  <ul>
<li><a class="reference internal" href="#">5. Built-in Exceptions</a><ul>
<li><a class="reference internal" href="#base-classes">5.1. Base classes</a></li>
<li><a class="reference internal" href="#concrete-exceptions">5.2. Concrete exceptions</a><ul>
<li><a class="reference internal" href="#os-exceptions">5.2.1. OS exceptions</a></li>
</ul>
</li>
<li><a class="reference internal" href="#warnings">5.3. Warnings</a></li>
<li><a class="reference internal" href="#exception-hierarchy">5.4. Exception hierarchy</a></li>
</ul>
</li>
</ul>

  <h4>Previous topic</h4>
  <p class="topless"><a href="stdtypes.html"
                        title="previous chapter">4. Built-in Types</a></p>
  <h4>Next topic</h4>
  <p class="topless"><a href="text.html"
                        title="next chapter">6. Text Processing Services</a></p>
<h3>This Page</h3>
<ul class="this-page-menu">
  <li><a href="../bugs.html">Report a Bug</a></li>
  <li><a href="../_sources/library/exceptions.txt"
         rel="nofollow">Show Source</a></li>
</ul>

<div id="searchbox" style="display: none">
  <h3>Quick search</h3>
    <form class="search" action="../search.html" method="get">
      <input type="text" name="q" />
      <input type="submit" value="Go" />
      <input type="hidden" name="check_keywords" value="yes" />
      <input type="hidden" name="area" value="default" />
    </form>
    <p class="searchtip" style="font-size: 90%">
    Enter search terms or a module, class or function name.
    </p>
</div>
<script type="text/javascript">$('#searchbox').show(0);</script>
        </div>
      </div>
      <div class="clearer"></div>
    </div>  
    <div class="related">
      <h3>Navigation</h3>
      <ul>
        <li class="right" style="margin-right: 10px">
          <a href="../genindex.html" title="General Index"
             >index</a></li>
        <li class="right" >
          <a href="../py-modindex.html" title="Python Module Index"
             >modules</a> |</li>
        <li class="right" >
          <a href="text.html" title="6. Text Processing Services"
             >next</a> |</li>
        <li class="right" >
          <a href="stdtypes.html" title="4. Built-in Types"
             >previous</a> |</li>
        <li><img src="../_static/py.png" alt=""
                 style="vertical-align: middle; margin-top: -1px"/></li>
        <li><a href="https://www.python.org/">Python</a> &raquo;</li>
        <li>
          <span class="version_switcher_placeholder">3.4.3</span>
          <a href="../index.html">Documentation</a> &raquo;
        </li>

          <li><a href="index.html" >The Python Standard Library</a> &raquo;</li> 
      </ul>
    </div>  
    <div class="footer">
    &copy; <a href="../copyright.html">Copyright</a> 1990-2015, Python Software Foundation.
    <br />
    The Python Software Foundation is a non-profit corporation.
    <a href="https://www.python.org/psf/donations/">Please donate.</a>
    <br />
    Last updated on Mar 10, 2015.
    <a href="../bugs.html">Found a bug</a>?
    <br />
    Created using <a href="http://sphinx.pocoo.org/">Sphinx</a> 1.2.3.
    </div>

  </body>
</html>